const jpColors = {
  'primary': '#204372',
  'mediumPrimary': '#778da3',
  'blackPrimary': '#050c1c',
  'darkPrimary': '#0C1D4A',
  'lightPrimary': '#b8c1cb',
  'secondary': '#3E98C7',
  'mediumSecondary': '#84bbd2',
  'lightSecondary': '#bed4de',
  'accent': '#F5A818',
  'mediumAccent': '#e9b580',
  'lightAccent': '#e8d3bc',
  'background': '#F1F1F1',
  'secondaryBackground': '#DEDEDE',
  'surface': '#FCFCFC',
  'error': '#F54531',
  'success': '#36B369',
  'pending': '#C6F500',
  'textInBackground': '#656565',
  'textInSurface': '#1D1D1D',
};


const colors = {
  'black': '#333740',
  'white': '#ffffff',
  'orange': jpColors.accent,
  'lightOrange': jpColors.lightAccent,
  'red': jpColors.error,
  'yellow': jpColors.accent,
  'green': jpColors.success,
  'blue': jpColors.primary,
  'teal': jpColors.mediumSecondary,
  'pink': jpColors.accent,
  'purple': jpColors.primary,
  'gray': '#464a4c',
  'border': '#e3e9f3',
  'gray-dark': '#292b2c',
  'grayLight': '#636c72',
  'gray-lighter': '#eceeef',
  'gray-lightest': '#f7f7f9',
  'brightGrey': '#f0f3f8',
  'darkGrey': '#e3e9f3',
  'lightGrey': '#fafafa',
  'lightestGrey': '#fbfbfb',
  'mediumGrey': '#f2f3f4',
  'grey': '#9ea7b8',
  'greyDark': '#292b2c',
  'greyAlpha': 'rgba(227, 233, 243, 0.5)',
  'lightestBlue': '#e4f0fc',
  'lightBlue': '#e6f0fb',
  'mediumBlue': jpColors.primary,
  'darkBlue': jpColors.darkPrimary,
  'pale': '#f7f8f8',
  'content': {
    'background': jpColors.background,
    'background-alpha': 'rgba(14, 22, 34, 0.02)',
  },
  'leftMenu': {
    'link-hover': '#1c2431',
    'link-color': '#919bae',
    'title-color': '#5b626f',
    'background-header-link': jpColors.primary,
  },
  'strapi': {
    'gray-light': '#eff3f6',
    'gray': '#535f76',
    'blue-darker': '#18202e',
    'blue-dark': '#151c2e',
    'blue': jpColors.primary,
  },
  ...jpColors,


};

export default colors;
